### ISSUE TITLE
Inconsistency in colors from `useThemeParams` and CSS variables

### ISSUE THREAD

**Issue by thecoorum** [Telegram-Mini-Apps/telegram-apps#169] opened 2023-11-06 15:23 UTC
**Platform**

Select one of the following:

[//]: # (To make as selected, use [x] instead of [ ].)

- [ ] Telegram for Android
- [x] Telegram for iOS
- [ ] Telegram for macOS
- [ ] Telegram Desktop
- [ ] Telegram Web A
- [ ] Telegram Web K

**Describe the bug**

**To Reproduce**

1. Configure `SDKProvider` with `initOptions` to be `{ cssVars: true }` to have access to variables
2. Create a `div` with background set to either `--tg-bg-color` or to `backgroundColor` received from `useThemeParams` hook
3. Open the Mini App in iOS app and macOS/WebK and see different colors for the same theme (iOS background color differs from the header color)

**Expected behavior**

Color of the `div` should be the same as the header color

**Media**
_iOS_
<img width="410" alt="image" src="https://github.com/Telegram-Mini-Apps/tma.js/assets/32096016/ed95a781-8734-40c3-82d7-9056e0999b00">

_macOS_
<img width="410" alt="image" src="https://github.com/Telegram-Mini-Apps/tma.js/assets/32096016/d3a0b4e2-b5ac-4e72-89ab-9630021a95d4">

_WebK_
![image](https://github.com/Telegram-Mini-Apps/tma.js/assets/32096016/0cb809eb-4979-4e83-8c88-e30942be6b0f)

**Comment by thecoorum** [comment] 2023-11-06 15:25
Also, from the screen you might notice that the WebK doesn't render the Main Button, despite that the same screen was captured. Probably need to open a separate issue for that one (the Main Button was also unresponsive on iOS for some reason)

**Comment by heyqbnk** [comment] 2023-11-06 18:21
I am not sure this problem is related to the packages themselves. None of the packages responsible for what Telegram application sends to the Mini App. You could see these differences not only due to incorrect packages behavior, but also differences between Telegram platforms.

So we should only call it a bug in case the result is incorrect according to what was expected in the specific platform. So, if Telegram for iOS application sent us bg_color #000000 and Telegram for Android sent #010101, this is not a bug, it is just a different behavior.

Is this the case?

**Comment by thecoorum** [comment] 2023-11-08 13:54
Yeah, makes sense. Closing this one

**Comment by wishyoudie** [comment] 2024-08-04 08:22
Reopening because this seems like SDK bug after all. Here are three screenshots of the 'same' app. I've opened ThemeParams page to demonstrate how `secondary_bg_color` is different across them.

Screenshot 1 (tma-dl) is `@telegram-apps/sdk` opened via Direct Link (more precisely, the new Open App button in bot's profile, but the behaviour remains consistent with Direct Links). 

Screenshot 2 (tma-mb) is `@telegram-apps/sdk` opened via Menu Button. 

Screenshot 3 (tg-dl) and Screenshot 4 (tg-mb) are using Telegram's sdk (bootstrapped with create-mini-app).

As you can see from these images, three out of four combinations have `secondary_bg_color` set to `#1c1c1d`, meanwhile in Direct Link + ta/sdk it is `#000000`, which is not correct.

I only encountered this issue with Telegram for iOS. Desktop and macOS versions seem to not have this bug, can't say anything about Android though.

![tma-dl](https://github.com/user-attachments/assets/135ab78e-b652-40db-b6e6-b7b4a129bc8b)
![tma-mb](https://github.com/user-attachments/assets/4bd4a84d-e7b7-452a-a5d9-87cd5aa85b88)
![tg-dl](https://github.com/user-attachments/assets/f5a54fa5-3262-4889-9d4d-ae274cda656f)
![tg-mb](https://github.com/user-attachments/assets/0a6745ef-ff63-4f61-a3c9-7b323ed1a3ef)

**Comment by wishyoudie** [comment] 2024-08-25 06:51
I was able to fix this issue by manually requesting themeParams. For React.js template you can add another effect to `App` component:

```ts
import { postEvent } from "@telegram-apps/sdk-react";

// ...

useEffect(() => {
    postEvent("web_app_request_theme");
  }, []);

```

Since logging is disabled during SDK initialization even with `debug={true}` prop, I wasn't able to track whether or not SDK calls this event implicitly, contrary to tsdk which has completely opposite behaviour in this regard (not quite good either way). The same React app works perfectly on iOS when scaffolded with tsdk and gives the following console output on start:

> [Telegram.WebView] > postEvent web_app_set_header_color {color_key: 'bg_color'}
> [Telegram.WebView] > postEvent web_app_set_background_color {color: '#ffffff'}
> [Telegram.WebView] > postEvent web_app_request_theme
> [Telegram.WebView] > postEvent web_app_request_viewport
> [Telegram.WebView] < receiveEvent theme_changed {theme_params: {…}}
> [Telegram.WebView] > postEvent web_app_setup_main_button {is_visible: false}

My guess would be that either SDK does not handle request_theme response correctly or that the following funny lines in `telegram-web-apps.js` kick in (L383 - L387):

```js
// temp iOS fix
        if (theme_params.bg_color == '#1c1c1d' &&
            theme_params.bg_color == theme_params.secondary_bg_color) {
            theme_params.secondary_bg_color = '#2c2c2e';
        }
```

**Comment by heyqbnk** [comment] 2024-09-30 21:51
Closing due to the problem is not on the SDK side, unfortunately

**Closed** 2024-09-30 21:52 UTC
Labels: bug
