### ISSUE TITLE
[Bug]: openTelegramLink does not close app on iOS

### ISSUE THREAD

**Issue by webdeb** [Telegram-Mini-Apps/telegram-apps#326] opened 2024-05-21 22:15 UTC
### Telegram Application

Telegram for iOS

### Describe the Bug

openTelegramLink does not close app on iOS when the mini app was opened from the same url (bot)

### To Reproduce

Call `openTelegramLink` in an app which was opened on the same url. 

### Expected Behavior

openTelegramLink closes the app, goes to the desired target.

**Comment by heyqbnk** [comment] 2024-05-22 07:51
Hey. What is the use case for opening the same app with the same url?

**Comment by webdeb** [comment] 2024-05-22 22:17
Hi Vladislav, the use case is the following: user clicks on "get invite link", so I generate one and send it via the bot, close the app, so the user can forward the message. I also found a workaround with `miniApp.close()`

**Comment by recallyourname** [comment] 2024-05-29 05:07
Same happened to me when i was implementing the payment gateway: https://pay.wallet.tg/ 

Looked pretty native at first glance (until i realized it is indeed a bug)

**Comment by heyqbnk** [comment] 2024-09-30 21:53
Closing, the problem is on the platform side. Will not add manual `close()` call, because it may break something else

**Closed by heyqbnk** 2024-09-30 21:53 UTC
Labels: bug
